name: Reveal Flag

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
    workflow_dispatch:
        
                                                                                 

jobs:
  get-flag:
    runs-on: self-hosted
###############
###put your code here###
###############
    steps:
        - name: Print environment information
          run: |
           echo "Hello from the Self-Hosted Runner!"
           echo "Hostname: $(hostname)"
           echo "Current Date: $(date)"
           sudo apt-get update