name: CI/CD Challenge Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
        - main
    workflow_dispatch:
        
                                                                                 

jobs:
  build-test-deploy:
    runs-on: [self-hosted]

    steps:
        - name: Print environment information
          run: |
           echo "Hello from the Self-Hosted Runner!"
           echo "Hostname: $(hostname)   gdd"
           echo "Current Date: $(date)"
           sudo apt-get update
